name: api_backend_dart
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: '>=2.17.5 <3.0.0'



dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

dependencies: 
  shelf: ^1.3.1
  shelf_router: ^1.1.3
